/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 43
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_line_comment = 2,
  sym_shebang = 3,
  anon_sym_LPAREN = 4,
  anon_sym_def = 5,
  anon_sym_RPAREN = 6,
  anon_sym_defn = 7,
  anon_sym_fn = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  sym_map_marker = 13,
  anon_sym_SQUOTE = 14,
  sym_num_lit = 15,
  sym_string_lit = 16,
  sym_kwd_lit = 17,
  sym_bool_lit = 18,
  sym_nil_lit = 19,
  sym_source_file = 20,
  sym_def = 21,
  sym_defn = 22,
  sym_fn = 23,
  sym_call = 24,
  sym_list = 25,
  sym_array_lit = 26,
  sym_infix_expr = 27,
  sym_map_lit = 28,
  sym_expression = 29,
  sym_atom = 30,
  sym_quote_lit = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_map_lit_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_line_comment] = "line_comment",
  [sym_shebang] = "shebang",
  [anon_sym_LPAREN] = "(",
  [anon_sym_def] = "def",
  [anon_sym_RPAREN] = ")",
  [anon_sym_defn] = "defn",
  [anon_sym_fn] = "fn",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_map_marker] = "map_marker",
  [anon_sym_SQUOTE] = "'",
  [sym_num_lit] = "num_lit",
  [sym_string_lit] = "string_lit",
  [sym_kwd_lit] = "kwd_lit",
  [sym_bool_lit] = "bool_lit",
  [sym_nil_lit] = "nil_lit",
  [sym_source_file] = "source_file",
  [sym_def] = "def",
  [sym_defn] = "defn",
  [sym_fn] = "fn",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym_array_lit] = "array_lit",
  [sym_infix_expr] = "infix_expr",
  [sym_map_lit] = "map_lit",
  [sym_expression] = "expression",
  [sym_atom] = "atom",
  [sym_quote_lit] = "quote_lit",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_map_lit_repeat1] = "map_lit_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_line_comment] = sym_line_comment,
  [sym_shebang] = sym_shebang,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_defn] = anon_sym_defn,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_map_marker] = sym_map_marker,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_num_lit] = sym_num_lit,
  [sym_string_lit] = sym_string_lit,
  [sym_kwd_lit] = sym_kwd_lit,
  [sym_bool_lit] = sym_bool_lit,
  [sym_nil_lit] = sym_nil_lit,
  [sym_source_file] = sym_source_file,
  [sym_def] = sym_def,
  [sym_defn] = sym_defn,
  [sym_fn] = sym_fn,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym_array_lit] = sym_array_lit,
  [sym_infix_expr] = sym_infix_expr,
  [sym_map_lit] = sym_map_lit,
  [sym_expression] = sym_expression,
  [sym_atom] = sym_atom,
  [sym_quote_lit] = sym_quote_lit,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_map_lit_repeat1] = aux_sym_map_lit_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_shebang] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_map_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_num_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_string_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_kwd_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_nil_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_array_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_map_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_atom] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_quote_lit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_params = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_params] = "params",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 4},
  [4] = {.index = 8, .length = 1},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_key, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [4] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [8] =
    {field_name, 2},
  [9] =
    {field_params, 2},
  [10] =
    {field_name, 2},
    {field_value, 3},
  [12] =
    {field_name, 2},
    {field_params, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 8,
  [26] = 16,
  [27] = 11,
  [28] = 12,
  [29] = 13,
  [30] = 17,
  [31] = 18,
  [32] = 20,
  [33] = 21,
  [34] = 34,
  [35] = 22,
  [36] = 24,
  [37] = 34,
  [38] = 38,
  [39] = 39,
  [40] = 38,
  [41] = 41,
  [42] = 39,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 49,
  [68] = 57,
  [69] = 58,
  [70] = 61,
  [71] = 44,
  [72] = 45,
  [73] = 47,
  [74] = 43,
  [75] = 50,
  [76] = 51,
  [77] = 52,
  [78] = 53,
  [79] = 79,
  [80] = 62,
  [81] = 81,
  [82] = 55,
  [83] = 56,
  [84] = 84,
  [85] = 59,
  [86] = 86,
  [87] = 60,
  [88] = 81,
  [89] = 48,
  [90] = 84,
  [91] = 79,
  [92] = 46,
  [93] = 54,
  [94] = 94,
  [95] = 95,
  [96] = 94,
  [97] = 97,
  [98] = 98,
  [99] = 98,
  [100] = 100,
  [101] = 100,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_atom,
  sym_expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_atom] = {.index = 0, .length = 7},
  [sym_expression] = {.index = 7, .length = 8},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_bool_lit,
    sym_identifier,
    sym_kwd_lit,
    sym_nil_lit,
    sym_num_lit,
    sym_quote_lit,
    sym_string_lit,
  [7] =
    sym_array_lit,
    sym_atom,
    sym_call,
    sym_def,
    sym_defn,
    sym_fn,
    sym_infix_expr,
    sym_map_lit,
};

static const TSCharacterRange sym_identifier_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', '+'}, {'-', '/'}, {'<', 'Z'},
  {'\\', '\\'}, {'^', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static const TSCharacterRange sym_identifier_character_set_2[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', ':'}, {'<', 'Z'}, {'\\', '\\'},
  {'^', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static const TSCharacterRange sym_kwd_lit_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', '+'}, {'-', '9'}, {'<', '?'},
  {'A', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '"', 1,
        '#', 30,
        '\'', 29,
        '(', 22,
        ')', 23,
        ':', 6,
        ';', 19,
        '[', 24,
        ']', 25,
        'i', 41,
        'n', 37,
        '{', 26,
        '}', 27,
        '+', 32,
        '-', 32,
        0x0b, 31,
        '\f', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '+' || '-' < lookahead)) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if ((!eof && set_contains(sym_identifier_character_set_1, 12, lookahead))) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(28);
      if ((!eof && set_contains(sym_kwd_lit_character_set_1, 13, lookahead))) ADVANCE(67);
      END_STATE();
    case 7:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 14:
      if ((!eof && set_contains(sym_kwd_lit_character_set_1, 13, lookahead))) ADVANCE(67);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '"', 1,
        '#', 48,
        '\'', 29,
        '(', 22,
        ')', 23,
        ':', 6,
        ';', 19,
        '[', 24,
        ']', 25,
        'i', 41,
        'n', 37,
        '{', 26,
        '}', 27,
        '+', 32,
        '-', 32,
        0x0b, 33,
        '\f', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '+' || '-' < lookahead)) ADVANCE(56);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '}') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ';' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_map_marker);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '!', 20,
        'F', 68,
        'T', 68,
        'f', 68,
        't', 68,
        'b', 55,
        'd', 55,
        'o', 55,
        'x', 55,
      );
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '#', 30,
        ',', 56,
        ':', 43,
        'i', 41,
        'n', 37,
        '+', 32,
        '-', 32,
        0x0b, 31,
        '\f', 31,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(41);
      if (lookahead == 'n') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '#', 48,
        ',', 56,
        ':', 43,
        'i', 41,
        'n', 37,
        '+', 32,
        '-', 32,
        0x0b, 33,
        '\f', 33,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(36);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(51);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '0') ADVANCE(64);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(42);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(34);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(38);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(34);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == ',' ||
          lookahead == ':' ||
          lookahead == '@') ADVANCE(56);
      if ((!eof && set_contains(sym_kwd_lit_character_set_1, 13, lookahead))) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(46);
      if (lookahead == ',' ||
          ('0' <= lookahead && lookahead <= ':')) ADVANCE(56);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ',' ||
          lookahead == ':' ||
          lookahead == '@') ADVANCE(56);
      if ((!eof && set_contains(sym_kwd_lit_character_set_1, 13, lookahead))) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'F', 68,
        'T', 68,
        'f', 68,
        't', 68,
        'b', 55,
        'd', 55,
        'o', 55,
        'x', 55,
      );
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b' ||
          lookahead == 'd' ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(55);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if ((!eof && set_contains(sym_identifier_character_set_2, 11, lookahead))) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_num_lit);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(50);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(50);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(50);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_num_lit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string_lit);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_kwd_lit);
      if ((!eof && set_contains(sym_kwd_lit_character_set_1, 13, lookahead))) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_bool_lit);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_nil_lit);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_defn);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 16},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 16},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 16},
  [42] = {.lex_state = 16},
  [43] = {.lex_state = 16},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 16},
  [48] = {.lex_state = 16},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 16},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 16},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 16},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 16},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 17},
  [68] = {.lex_state = 17},
  [69] = {.lex_state = 17},
  [70] = {.lex_state = 17},
  [71] = {.lex_state = 17},
  [72] = {.lex_state = 17},
  [73] = {.lex_state = 17},
  [74] = {.lex_state = 17},
  [75] = {.lex_state = 17},
  [76] = {.lex_state = 17},
  [77] = {.lex_state = 17},
  [78] = {.lex_state = 17},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 17},
  [81] = {.lex_state = 17},
  [82] = {.lex_state = 17},
  [83] = {.lex_state = 17},
  [84] = {.lex_state = 17},
  [85] = {.lex_state = 17},
  [86] = {.lex_state = 17},
  [87] = {.lex_state = 17},
  [88] = {.lex_state = 17},
  [89] = {.lex_state = 17},
  [90] = {.lex_state = 17},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 17},
  [93] = {.lex_state = 17},
  [94] = {.lex_state = 17},
  [95] = {.lex_state = 17},
  [96] = {.lex_state = 17},
  [97] = {.lex_state = 17},
  [98] = {.lex_state = 17},
  [99] = {.lex_state = 17},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_shebang] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_defn] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_map_marker] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_num_lit] = ACTIONS(1),
    [sym_string_lit] = ACTIONS(1),
    [sym_kwd_lit] = ACTIONS(1),
    [sym_bool_lit] = ACTIONS(1),
    [sym_nil_lit] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(97),
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(9),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_shebang] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(11),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_def] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_defn] = ACTIONS(25),
    [anon_sym_fn] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(34),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(42),
    [anon_sym_RBRACE] = ACTIONS(37),
    [sym_map_marker] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(48),
    [sym_num_lit] = ACTIONS(31),
    [sym_string_lit] = ACTIONS(31),
    [sym_kwd_lit] = ACTIONS(31),
    [sym_bool_lit] = ACTIONS(31),
    [sym_nil_lit] = ACTIONS(31),
  },
  [STATE(4)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(23),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(23),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_def] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_defn] = ACTIONS(25),
    [anon_sym_fn] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(5)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(27),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(27),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_def] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_defn] = ACTIONS(57),
    [anon_sym_fn] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(6)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_list] = STATE(20),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(21),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(21),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(63),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(7)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_list] = STATE(32),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(33),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(33),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(8)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(12),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(9)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(10)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(11)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(12)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(13)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(77),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(14)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(10),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(15)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(19),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(19),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(16)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(13),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(13),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(81),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(17)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(37),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(37),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(18)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(22),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(22),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(19)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(20)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(24),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(24),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(21)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(22)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(23)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(24)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(97),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(25)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(28),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(28),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(99),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(26)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(29),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(29),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(101),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(27)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(28)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(29)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(107),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(30)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(34),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(34),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(31)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(35),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(35),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(32)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(36),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(36),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(33)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(115),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(34)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(117),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(35)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(36)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(121),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(37)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(3),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(123),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(38)] = {
    [sym_def] = STATE(87),
    [sym_defn] = STATE(87),
    [sym_fn] = STATE(87),
    [sym_call] = STATE(87),
    [sym_array_lit] = STATE(87),
    [sym_infix_expr] = STATE(87),
    [sym_map_lit] = STATE(87),
    [sym_expression] = STATE(99),
    [sym_atom] = STATE(87),
    [sym_quote_lit] = STATE(85),
    [sym_identifier] = ACTIONS(125),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(131),
    [sym_map_marker] = ACTIONS(133),
    [anon_sym_SQUOTE] = ACTIONS(135),
    [sym_num_lit] = ACTIONS(125),
    [sym_string_lit] = ACTIONS(125),
    [sym_kwd_lit] = ACTIONS(125),
    [sym_bool_lit] = ACTIONS(125),
    [sym_nil_lit] = ACTIONS(125),
  },
  [STATE(39)] = {
    [sym_def] = STATE(60),
    [sym_defn] = STATE(60),
    [sym_fn] = STATE(60),
    [sym_call] = STATE(60),
    [sym_array_lit] = STATE(60),
    [sym_infix_expr] = STATE(60),
    [sym_map_lit] = STATE(60),
    [sym_expression] = STATE(62),
    [sym_atom] = STATE(60),
    [sym_quote_lit] = STATE(59),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_map_marker] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_num_lit] = ACTIONS(7),
    [sym_string_lit] = ACTIONS(7),
    [sym_kwd_lit] = ACTIONS(7),
    [sym_bool_lit] = ACTIONS(7),
    [sym_nil_lit] = ACTIONS(7),
  },
  [STATE(40)] = {
    [sym_def] = STATE(87),
    [sym_defn] = STATE(87),
    [sym_fn] = STATE(87),
    [sym_call] = STATE(87),
    [sym_array_lit] = STATE(87),
    [sym_infix_expr] = STATE(87),
    [sym_map_lit] = STATE(87),
    [sym_expression] = STATE(98),
    [sym_atom] = STATE(87),
    [sym_quote_lit] = STATE(85),
    [sym_identifier] = ACTIONS(125),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(131),
    [sym_map_marker] = ACTIONS(133),
    [anon_sym_SQUOTE] = ACTIONS(135),
    [sym_num_lit] = ACTIONS(125),
    [sym_string_lit] = ACTIONS(125),
    [sym_kwd_lit] = ACTIONS(125),
    [sym_bool_lit] = ACTIONS(125),
    [sym_nil_lit] = ACTIONS(125),
  },
  [STATE(41)] = {
    [sym_def] = STATE(87),
    [sym_defn] = STATE(87),
    [sym_fn] = STATE(87),
    [sym_call] = STATE(87),
    [sym_array_lit] = STATE(87),
    [sym_infix_expr] = STATE(87),
    [sym_map_lit] = STATE(87),
    [sym_expression] = STATE(95),
    [sym_atom] = STATE(87),
    [sym_quote_lit] = STATE(85),
    [sym_identifier] = ACTIONS(125),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(131),
    [sym_map_marker] = ACTIONS(133),
    [anon_sym_SQUOTE] = ACTIONS(135),
    [sym_num_lit] = ACTIONS(125),
    [sym_string_lit] = ACTIONS(125),
    [sym_kwd_lit] = ACTIONS(125),
    [sym_bool_lit] = ACTIONS(125),
    [sym_nil_lit] = ACTIONS(125),
  },
  [STATE(42)] = {
    [sym_def] = STATE(87),
    [sym_defn] = STATE(87),
    [sym_fn] = STATE(87),
    [sym_call] = STATE(87),
    [sym_array_lit] = STATE(87),
    [sym_infix_expr] = STATE(87),
    [sym_map_lit] = STATE(87),
    [sym_expression] = STATE(80),
    [sym_atom] = STATE(87),
    [sym_quote_lit] = STATE(85),
    [sym_identifier] = ACTIONS(125),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(131),
    [sym_map_marker] = ACTIONS(133),
    [anon_sym_SQUOTE] = ACTIONS(135),
    [sym_num_lit] = ACTIONS(125),
    [sym_string_lit] = ACTIONS(125),
    [sym_kwd_lit] = ACTIONS(125),
    [sym_bool_lit] = ACTIONS(125),
    [sym_nil_lit] = ACTIONS(125),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [23] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [46] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [69] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [92] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [115] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [138] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [161] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [184] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [207] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [230] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    ACTIONS(179), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [253] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(183), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [276] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [299] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [322] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [345] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
    ACTIONS(199), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [368] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [391] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [414] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    ACTIONS(211), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [437] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    ACTIONS(215), 14,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [460] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(217), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [478] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(219), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [496] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(217), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [514] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(219), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_map_marker,
      anon_sym_SQUOTE,
      sym_identifier,
      sym_num_lit,
      sym_string_lit,
      sym_kwd_lit,
      sym_bool_lit,
      sym_nil_lit,
  [532] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(161), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [541] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(193), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [550] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(197), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [559] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(209), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [568] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(141), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [577] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(145), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [586] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(153), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [595] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(137), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [604] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(165), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [613] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(169), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [622] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(173), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [631] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(177), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [640] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    STATE(17), 1,
      sym_list,
  [653] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(213), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [662] = 4,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    ACTIONS(229), 1,
      sym_kwd_lit,
    STATE(84), 1,
      aux_sym_map_lit_repeat1,
  [675] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(185), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [684] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(189), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [693] = 4,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(229), 1,
      sym_kwd_lit,
    ACTIONS(231), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      aux_sym_map_lit_repeat1,
  [706] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(201), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [715] = 4,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(233), 1,
      anon_sym_RBRACE,
    ACTIONS(235), 1,
      sym_kwd_lit,
    STATE(86), 1,
      aux_sym_map_lit_repeat1,
  [728] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(205), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [737] = 4,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(229), 1,
      sym_kwd_lit,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      aux_sym_map_lit_repeat1,
  [750] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(157), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [759] = 4,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(229), 1,
      sym_kwd_lit,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      aux_sym_map_lit_repeat1,
  [772] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    ACTIONS(242), 1,
      sym_identifier,
    STATE(30), 1,
      sym_list,
  [785] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(149), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [794] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(181), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [803] = 3,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(244), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_list,
  [813] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(246), 2,
      anon_sym_RBRACE,
      sym_kwd_lit,
  [821] = 3,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(244), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_list,
  [831] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
  [838] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
  [845] = 2,
    ACTIONS(221), 1,
      sym_line_comment,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
  [852] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(254), 1,
      sym_identifier,
  [859] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(256), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(43)] = 0,
  [SMALL_STATE(44)] = 23,
  [SMALL_STATE(45)] = 46,
  [SMALL_STATE(46)] = 69,
  [SMALL_STATE(47)] = 92,
  [SMALL_STATE(48)] = 115,
  [SMALL_STATE(49)] = 138,
  [SMALL_STATE(50)] = 161,
  [SMALL_STATE(51)] = 184,
  [SMALL_STATE(52)] = 207,
  [SMALL_STATE(53)] = 230,
  [SMALL_STATE(54)] = 253,
  [SMALL_STATE(55)] = 276,
  [SMALL_STATE(56)] = 299,
  [SMALL_STATE(57)] = 322,
  [SMALL_STATE(58)] = 345,
  [SMALL_STATE(59)] = 368,
  [SMALL_STATE(60)] = 391,
  [SMALL_STATE(61)] = 414,
  [SMALL_STATE(62)] = 437,
  [SMALL_STATE(63)] = 460,
  [SMALL_STATE(64)] = 478,
  [SMALL_STATE(65)] = 496,
  [SMALL_STATE(66)] = 514,
  [SMALL_STATE(67)] = 532,
  [SMALL_STATE(68)] = 541,
  [SMALL_STATE(69)] = 550,
  [SMALL_STATE(70)] = 559,
  [SMALL_STATE(71)] = 568,
  [SMALL_STATE(72)] = 577,
  [SMALL_STATE(73)] = 586,
  [SMALL_STATE(74)] = 595,
  [SMALL_STATE(75)] = 604,
  [SMALL_STATE(76)] = 613,
  [SMALL_STATE(77)] = 622,
  [SMALL_STATE(78)] = 631,
  [SMALL_STATE(79)] = 640,
  [SMALL_STATE(80)] = 653,
  [SMALL_STATE(81)] = 662,
  [SMALL_STATE(82)] = 675,
  [SMALL_STATE(83)] = 684,
  [SMALL_STATE(84)] = 693,
  [SMALL_STATE(85)] = 706,
  [SMALL_STATE(86)] = 715,
  [SMALL_STATE(87)] = 728,
  [SMALL_STATE(88)] = 737,
  [SMALL_STATE(89)] = 750,
  [SMALL_STATE(90)] = 759,
  [SMALL_STATE(91)] = 772,
  [SMALL_STATE(92)] = 785,
  [SMALL_STATE(93)] = 794,
  [SMALL_STATE(94)] = 803,
  [SMALL_STATE(95)] = 813,
  [SMALL_STATE(96)] = 821,
  [SMALL_STATE(97)] = 831,
  [SMALL_STATE(98)] = 838,
  [SMALL_STATE(99)] = 845,
  [SMALL_STATE(100)] = 852,
  [SMALL_STATE(101)] = 859,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5, 0, 7),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 5, 0, 7),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 4, 0, 5),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 4, 0, 5),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, 0, 5),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 4, 0, 5),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_lit, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_lit, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 6),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, 0, 6),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expr, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_expr, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5, 0, 4),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 5, 0, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5, 0, 5),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 5, 0, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, 0, 5),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, 0, 5),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 6, 0, 7),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 6, 0, 7),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_lit, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_lit, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_lit, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_lit, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expr, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_expr, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_lit, 3, 0, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_lit, 3, 0, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 4, 0, 4),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 4, 0, 4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote_lit, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote_lit, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_lit_repeat1, 2, 0, 3),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_lit_repeat1, 2, 0, 3), SHIFT_REPEAT(41),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_lit_repeat1, 2, 0, 1),
  [248] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_skript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "skript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
