/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  aux_sym_line_comment_token1 = 3,
  anon_sym_LPAREN = 4,
  anon_sym_def = 5,
  anon_sym_RPAREN = 6,
  anon_sym_defn = 7,
  anon_sym_fn = 8,
  sym_symbol_literal = 9,
  sym_integer_literal = 10,
  sym_decimal_literal = 11,
  sym_shebang = 12,
  sym_source_file = 13,
  sym_line_comment = 14,
  sym_def = 15,
  sym_defn = 16,
  sym_fn = 17,
  sym_call = 18,
  sym_list = 19,
  sym_expression = 20,
  sym_atom = 21,
  sym_literal = 22,
  aux_sym_source_file_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_def] = "def",
  [anon_sym_RPAREN] = ")",
  [anon_sym_defn] = "defn",
  [anon_sym_fn] = "fn",
  [sym_symbol_literal] = "symbol_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_shebang] = "shebang",
  [sym_source_file] = "source_file",
  [sym_line_comment] = "line_comment",
  [sym_def] = "def",
  [sym_defn] = "defn",
  [sym_fn] = "fn",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym_expression] = "expression",
  [sym_atom] = "atom",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_defn] = anon_sym_defn,
  [anon_sym_fn] = anon_sym_fn,
  [sym_symbol_literal] = sym_symbol_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_shebang] = sym_shebang,
  [sym_source_file] = sym_source_file,
  [sym_line_comment] = sym_line_comment,
  [sym_def] = sym_def,
  [sym_defn] = sym_defn,
  [sym_fn] = sym_fn,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym_expression] = sym_expression,
  [sym_atom] = sym_atom,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_shebang] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_atom] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_atom,
  sym_expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_atom] = {.index = 0, .length = 2},
  [sym_expression] = {.index = 2, .length = 5},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_identifier,
    sym_literal,
  [2] =
    sym_atom,
    sym_call,
    sym_def,
    sym_defn,
    sym_fn,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == ';') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '[') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == ';') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(5);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(8);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          (lookahead < '0' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == ';') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_symbol_literal);
      if (lookahead != 0 &&
          (lookahead < '0' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_decimal_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('<' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '[') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_shebang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(5);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_defn);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_defn] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [sym_symbol_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_decimal_literal] = ACTIONS(1),
    [sym_shebang] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym_line_comment] = STATE(1),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
    [sym_shebang] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_line_comment] = STATE(2),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_def] = ACTIONS(19),
    [anon_sym_defn] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_line_comment] = STATE(3),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_RPAREN] = ACTIONS(25),
    [sym_symbol_literal] = ACTIONS(33),
    [sym_integer_literal] = ACTIONS(36),
    [sym_decimal_literal] = ACTIONS(33),
  },
  [STATE(4)] = {
    [sym_line_comment] = STATE(4),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym_line_comment] = STATE(5),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(6)] = {
    [sym_line_comment] = STATE(6),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(41),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(7)] = {
    [sym_line_comment] = STATE(7),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(8)] = {
    [sym_line_comment] = STATE(8),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(45),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(9)] = {
    [sym_line_comment] = STATE(9),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(14),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(10)] = {
    [sym_line_comment] = STATE(10),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(28),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(11)] = {
    [sym_line_comment] = STATE(11),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(29),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
  [STATE(12)] = {
    [sym_line_comment] = STATE(12),
    [sym_def] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_call] = STATE(16),
    [sym_expression] = STATE(27),
    [sym_atom] = STATE(16),
    [sym_literal] = STATE(13),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_symbol_literal] = ACTIONS(11),
    [sym_integer_literal] = ACTIONS(13),
    [sym_decimal_literal] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(49), 1,
      sym_integer_literal,
    STATE(13), 1,
      sym_line_comment,
    ACTIONS(47), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [18] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(53), 1,
      sym_integer_literal,
    STATE(14), 1,
      sym_line_comment,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [36] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(57), 1,
      sym_integer_literal,
    STATE(15), 1,
      sym_line_comment,
    ACTIONS(55), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [54] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(61), 1,
      sym_integer_literal,
    STATE(16), 1,
      sym_line_comment,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [72] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(65), 1,
      sym_integer_literal,
    STATE(17), 1,
      sym_line_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [90] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(69), 1,
      sym_integer_literal,
    STATE(18), 1,
      sym_line_comment,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [108] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(73), 1,
      sym_integer_literal,
    STATE(19), 1,
      sym_line_comment,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [126] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(77), 1,
      sym_integer_literal,
    STATE(20), 1,
      sym_line_comment,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [144] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(81), 1,
      sym_integer_literal,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(79), 4,
      anon_sym_LPAREN,
      sym_symbol_literal,
      sym_decimal_literal,
      sym_identifier,
  [160] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_list,
    STATE(22), 1,
      sym_line_comment,
  [173] = 4,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_list,
    STATE(23), 1,
      sym_line_comment,
  [186] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_line_comment,
  [196] = 3,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    ACTIONS(89), 1,
      aux_sym_line_comment_token1,
    STATE(25), 1,
      sym_line_comment,
  [206] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(91), 1,
      sym_identifier,
    STATE(26), 1,
      sym_line_comment,
  [216] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_line_comment,
  [226] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_line_comment,
  [236] = 3,
    ACTIONS(3), 1,
      anon_sym_SEMI,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      sym_line_comment,
  [246] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 18,
  [SMALL_STATE(15)] = 36,
  [SMALL_STATE(16)] = 54,
  [SMALL_STATE(17)] = 72,
  [SMALL_STATE(18)] = 90,
  [SMALL_STATE(19)] = 108,
  [SMALL_STATE(20)] = 126,
  [SMALL_STATE(21)] = 144,
  [SMALL_STATE(22)] = 160,
  [SMALL_STATE(23)] = 173,
  [SMALL_STATE(24)] = 186,
  [SMALL_STATE(25)] = 196,
  [SMALL_STATE(26)] = 206,
  [SMALL_STATE(27)] = 216,
  [SMALL_STATE(28)] = 226,
  [SMALL_STATE(29)] = 236,
  [SMALL_STATE(30)] = 246,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_skript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "skript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
